services:
  minecraft:
    build: .
    env_file: .env
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
    command: /bin/sh
    stdin_open: true
    tty: true
